WITH 
CTE_AT_MOR AS (    
    SELECT 
        REF_INFO, 
        EMP, 
        COD_EMP, 
        COBERTURA, 
        PRODUTO,
        REF_INFO - EXTRACT(YEAR FROM DATA_NASC) AS IDADE,
        CASE WHEN SEXO NOT IN (N'M', N'F', N'm', N'f') THEN N'UNI' ELSE SEXO END SEXO,
        SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) < REF_INFO AND 
            EXTRACT(YEAR FROM DATA_INGR) > 1900
            THEN 1 ELSE 0 END) AS QTDE_ESTOQUE_INICIAL,
        SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) = 1900 THEN 1 ELSE 0 END) AS QTDE_ESTOQUE_FINAL,
        SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) = REF_INFO THEN 1 ELSE 0 END) AS QTDE_ENTRADAS,
        SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) > 1900 THEN 1 ELSE 0 END) 
        AS QTDE_GERAL_AT
        
    FROM dados_parquet.at_mor_000
    WHERE 
        LINHA_VALIDA = 1
    GROUP BY 
        REF_INFO, EMP, COD_EMP, SEXO, COBERTURA, PRODUTO, REF_INFO - EXTRACT(YEAR FROM DATA_NASC), CASE WHEN SEXO NOT IN (N'M', N'F', N'm', N'f') THEN N'UNI' ELSE SEXO END
),
CTE_SA_MOR AS (
    SELECT 
        REF_INFO, 
        EMP, 
        COD_EMP, 
        COBERTURA, 
        PRODUTO,
        CASE WHEN SEXO NOT IN (N'M', N'F', N'm', N'f') THEN N'UNI' ELSE SEXO END SEXO,
        SUM(CASE WHEN MOT_SAIDA = 100 THEN 1 ELSE 0 END) AS OBITO_100,
        SUM(CASE WHEN MOT_SAIDA = 200 THEN 1 ELSE 0 END) AS OBITO_200,
        SUM(CASE WHEN MOT_SAIDA = 300 THEN 1 ELSE 0 END) AS OBITO_300,
        SUM(CASE WHEN MOT_SAIDA = 400 THEN 1 ELSE 0 END) AS ENTRADA_INVALIDEZ_400,
        SUM(CASE WHEN MOT_SAIDA = 500 THEN 1 ELSE 0 END) AS ENTRADA_INVALIDEZ_500,
        SUM(CASE WHEN MOT_SAIDA = 600 THEN 1 ELSE 0 END) AS ENTRADA_INVALIDEZ_600,
        SUM(CASE WHEN MOT_SAIDA = 700 THEN 1 ELSE 0 END) AS ENTRADA_INVALIDEZ_700,
        SUM(CASE WHEN MOT_SAIDA = 800 THEN 1 ELSE 0 END) AS APOSENTADORIA,
        SUM(CASE WHEN MOT_SAIDA = 900 THEN 1 ELSE 0 END) AS OUTRAS_SAIDAS,
        REF_INFO - EXTRACT(YEAR FROM DATA_NASC) AS IDADE,
        COUNT(*) AS QTDE_GERAL_SA
    FROM dados_parquet.sa_mor_000
    WHERE 
        LINHA_VALIDA = 1           
    GROUP BY 
        REF_INFO, EMP, COD_EMP, SEXO, COBERTURA, PRODUTO, REF_INFO - EXTRACT(YEAR FROM DATA_NASC), CASE WHEN SEXO NOT IN (N'M', N'F', N'm', N'f') THEN N'UNI' ELSE SEXO END
)
SELECT
    COALESCE(T1.REF_INFO,T2.REF_INFO) AS REF_INFO,
    COALESCE(T1.EMP,T2.EMP) AS EMP,
    COALESCE(T1.COD_EMP,T2.COD_EMP) AS COD_EMP,
    COALESCE(T1.COBERTURA,T2.COBERTURA) AS COBERTURA,
    COALESCE(T1.PRODUTO,T2.PRODUTO) AS PRODUTO,
    COALESCE(T1.SEXO,T2.SEXO) AS SEXO,
    COALESCE(T1.IDADE,T2.IDADE) AS IDADE_31_DEZ,
    T1.QTDE_GERAL_AT AS REGISTROS_AT,
    T1.QTDE_ESTOQUE_INICIAL AS ESTOQUE_INICIAL, 
    T1.QTDE_ESTOQUE_FINAL AS ESTOQUE_FINAL, 
    T1.QTDE_ENTRADAS AS ENTRADAS, 
    T1.QTDE_ESTOQUE_INICIAL + T1.QTDE_ENTRADAS - T1.QTDE_ESTOQUE_FINAL AS SAIDAS_CALCULADAS,
    ((T1.QTDE_ESTOQUE_INICIAL + T1.QTDE_ESTOQUE_FINAL)/2) AS  EXPOSICAO, 
    T2.QTDE_GERAL_SA AS REGISTROS_SA,
    T2.OBITO_100,
    T2.OBITO_200,
    T2.OBITO_300,
    T2.ENTRADA_INVALIDEZ_400,
    T2.ENTRADA_INVALIDEZ_500,
    T2.ENTRADA_INVALIDEZ_600,
    T2.ENTRADA_INVALIDEZ_700,
    T2.APOSENTADORIA,
    T2.OUTRAS_SAIDAS,
    (COALESCE(T2.OBITO_100, 0) + COALESCE(T2.OBITO_200, 0) + COALESCE(T2.OBITO_300, 0)) AS OBITOS,
    (COALESCE(T2.ENTRADA_INVALIDEZ_400, 0) + COALESCE(T2.ENTRADA_INVALIDEZ_500, 0) + COALESCE(T2.ENTRADA_INVALIDEZ_600, 0) + COALESCE(T2.ENTRADA_INVALIDEZ_700, 0)) AS ENTRADAS_INVALIDEZ
FROM CTE_AT_MOR T1
FULL OUTER JOIN CTE_SA_MOR T2
    ON  
        T1.REF_INFO = T2.REF_INFO 
        AND T1.COD_EMP = T2.COD_EMP
        AND T1.EMP = T2.EMP 
        AND T1.SEXO = T2.SEXO
        AND T1.IDADE = T2.IDADE
        AND T1.PRODUTO = T2.PRODUTO
        AND T1.COBERTURA = T2.COBERTURA;