

CREATE OR REPLACE VIEW TABELAO_VIEW_REG AS 
WITH 
CTE_AT_INV AS (    
    SELECT 
        REF_INFO, 
        EMP, 
        COD_EMP, 
        SEXO, 
        COBERTURA, 
        PRODUTO,
        REF_INFO - EXTRACT(YEAR FROM DATA_NASC) AS IDADE,
        SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) < REF_INFO AND 
            EXTRACT(YEAR FROM DATA_INGR) > 1900
            THEN 1 ELSE 0 END) AS QTDE_ESTOQUE_INICIAL,
        SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) = 1900 THEN 1 ELSE 0 END) AS QTDE_ESTOQUE_FINAL,
        SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) = REF_INFO THEN 1 ELSE 0 END) AS QTDE_ENTRADAS,
        SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) > 1900 THEN 1 ELSE 0 END) 
        AS QTDE_GERAL_AT
        
    FROM dados_parquet.at_inv_000
    WHERE 
        LINHA_VALIDA = 1
    GROUP BY 
        REF_INFO, EMP, COD_EMP, SEXO, COBERTURA, PRODUTO, REF_INFO - EXTRACT(YEAR FROM DATA_NASC)
),
CTE_SA_INV AS (
    SELECT 
        REF_INFO, 
        EMP, 
        COD_EMP, 
        SEXO, 
        COBERTURA, 
        PRODUTO,
        SUM(CASE WHEN MOT_SAIDA = 400 THEN 1 ELSE 0 END) AS INV_ACI,
        SUM(CASE WHEN MOT_SAIDA = 500 THEN 1 ELSE 0 END) AS INV_ACI_TB,
        SUM(CASE WHEN MOT_SAIDA = 600 THEN 1 ELSE 0 END) AS INV_DOE,
        SUM(CASE WHEN MOT_SAIDA = 700 THEN 1 ELSE 0 END) AS INV_DOE_TB,
        REF_INFO - EXTRACT(YEAR FROM DATA_NASC) AS IDADE,
        COUNT(*) AS QTDE_GERAL_SA
    FROM dados_parquet.sa_inv_000
    WHERE 
        LINHA_VALIDA = 1                
    GROUP BY 
        REF_INFO, EMP, COD_EMP, SEXO, COBERTURA, PRODUTO, REF_INFO - EXTRACT(YEAR FROM DATA_NASC)
)
SELECT
    COALESCE(T1.REF_INFO,T2.REF_INFO) AS REF_INFO,
    COALESCE(T1.EMP,T2.EMP) AS EMP,
    COALESCE(T1.COD_EMP,T2.COD_EMP) AS COD_EMP,
    COALESCE(T1.COBERTURA,T2.COBERTURA) AS COBERTURA,
    COALESCE(T1.SEXO,T2.SEXO) AS SEXO,
    COALESCE(T1.IDADE,T2.IDADE) AS IDADE,
    T1.QTDE_GERAL_AT AS REGISTROS_AT,
    T1.QTDE_ESTOQUE_INICIAL AS ESTOQUE_INICIAL, 
    T1.QTDE_ESTOQUE_FINAL AS ESTOQUE_FINAL, 
    T1.QTDE_ENTRADAS AS ENTRADAS, 
    T1.QTDE_ESTOQUE_INICIAL + T1.QTDE_ENTRADAS - T1.QTDE_ESTOQUE_FINAL AS SAIDAS_CALCULADAS,
    ((T1.QTDE_ESTOQUE_INICIAL + T1.QTDE_ESTOQUE_FINAL)/2) AS  EXPOSICAO, 
    T2.QTDE_GERAL_SA AS REGISTROS_SA,
    T2.INV_ACI, 
    T2.INV_ACI_TB, 
    T2.INV_DOE, 
    T2.INV_DOE_TB 
FROM CTE_AT_INV T1
FULL OUTER JOIN CTE_SA_INV T2
    ON  
        T1.REF_INFO = T2.REF_INFO 
        AND T1.COD_EMP = T2.COD_EMP
        AND T1.EMP = T2.EMP 
        AND T1.SEXO = T2.SEXO
        AND T1.IDADE = T2.IDADE
        AND T1.PRODUTO = T2.PRODUTO
        AND T1.COBERTURA = T2.COBERTURA;