
-- Contagem por cpf unico 
CREATE OR REPLACE TABLE TABELAO_CPF_UNI AS 
-- SUBCONSULTA PARA DADOS DA AT_INV
    WITH CTE_AT_INV AS
        (
        -- SELECIONO AS INFORMAÇÕES NECESSARIAS DA TABELA DE ATIVOS JÁ AGRUPADA POR CPF UNICO
        SELECT 
            REF_INFO, EMP, COD_EMP, COBERTURA, COUNT(*) AS QTDE_AT_CPF_UNI, PRODUTO,
            -- CALCULO ESTOQUES
            SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) < REF_INFO 
                AND EXTRACT(YEAR FROM DATA_INGR) > 1900 
                THEN 1 ELSE 0 END) AS QTDE_ESTOQUE_INICIAL,
            SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) = 1900 THEN 1 ELSE 0 END) AS QTDE_ESTOQUE_FINAL,
            SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) = REF_INFO THEN 1 ELSE 0 END) AS QTDE_ENTRADAS,
            -- CALCULO DO TOTAL REGISTROS NO AGRUPAMENTO, SEM CONSIDERAR AS REPETIÇÕES DE QUEM É ESTOQUE FINAL (EM TESE ESSA CONTA DEVERIA SER ESTOQUE_INICIAL+ENTRADAS) 
            SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) > 1900 THEN 1 ELSE 0 END) AS QTDE_GERAL_AT,
            -- CALCULO IDADE
            ROUND((2 * REF_INFO - EXTRACT(YEAR FROM MAX_DATA_NASC) - EXTRACT(YEAR FROM MIN_DATA_NASC)) / 2) AS IDADE_CORR
        FROM 
        ( -- Seleção de cpfs unicos na tabela de ativos
        SELECT REF_INFO, DATA_INGR, PRODUTO, EMP, COD_EMP, CPF, COBERTURA, -- Verificar criterio de escolha para a cobertura
            MIN(DATA_INGR) AS MIN_DATA_INGR,
            MAX(DATA_INGR) AS MAX_DATA_INGR,
            MIN(DATA_NASC) AS MIN_DATA_NASC,
            MAX(DATA_NASC) AS MAX_DATA_NASC
        FROM dados_parquet.at_inv_000 
        WHERE LINHA_VALIDA = 1
        GROUP BY REF_INFO, EMP, COD_EMP, CPF, COBERTURA, PRODUTO, DATA_INGR
        ) ATIVOS_INV_BASE

        GROUP BY REF_INFO, EMP, COD_EMP, COBERTURA, ROUND((2 * REF_INFO - EXTRACT(YEAR FROM MAX_DATA_NASC)- EXTRACT(YEAR FROM MIN_DATA_NASC)) / 2), PRODUTO),

    -- SUBCONSULTA PARA DADOS DA SA_INV
    CTE_SA_INV AS
        (-- SELECIONO AS INFORMAÇÕES NECESSARIAS DA TABELA DE SAIDA JÁ AGRUPADA POR CPF UNICO
        SELECT REF_INFO, EMP,  COD_EMP, COBERTURA, PRODUTO, COUNT(*) AS QTDE_SA_CPF_UNI,
            SUM(CASE WHEN MOT_SAIDA = 400 THEN 1 ELSE 0 END) AS INV_ACI,
            SUM(CASE WHEN MOT_SAIDA = 500 THEN 1 ELSE 0 END) AS INV_ACI_TB,
            SUM(CASE WHEN MOT_SAIDA = 600 THEN 1 ELSE 0 END) AS INV_DOE,
            SUM(CASE WHEN MOT_SAIDA = 700 THEN 1 ELSE 0 END) AS INV_DOE_TB,
            ROUND((2 * REF_INFO - EXTRACT(YEAR FROM MAX_DATA_NASC)- EXTRACT(YEAR FROM MIN_DATA_NASC)) / 2) AS IDADE_CORR

        FROM 
        ( -- Seleção de cpfs unicos na tabela de saida
        SELECT REF_INFO, EMP, COD_EMP, CPF, COBERTURA, MOT_SAIDA, PRODUTO,
            MIN(DATA_NASC) AS MIN_DATA_NASC,
            MAX(DATA_NASC) AS MAX_DATA_NASC
        FROM dados_parquet.sa_inv_000
        WHERE LINHA_VALIDA = 1
        GROUP BY REF_INFO, EMP, COD_EMP, CPF, COBERTURA, MOT_SAIDA, PRODUTO
        )  SAIDAS_INV_BASE

        GROUP BY REF_INFO, EMP, COD_EMP, COBERTURA, PRODUTO, ROUND((2 * REF_INFO - EXTRACT(YEAR FROM MAX_DATA_NASC)- EXTRACT(YEAR FROM MIN_DATA_NASC)) / 2))


    -- FULL OUTER JOIN 
        -- FOI FEITO COM INTUITO DE NAO EXCLUIR OS REGISTROS CORRESPONDENTES A UMA IDADE QUE SO TEM NA SA

    SELECT 
        COALESCE(T1.REF_INFO,T2.REF_INFO) AS REF_INFO, 
        COALESCE(T1.EMP,T2.EMP) AS EMP,
        COALESCE(T1.COD_EMP,T2.COD_EMP) AS COD_EMP,
        COALESCE(T1.COBERTURA,T2.COBERTURA) AS COBERTURA,
        COALESCE(T1.PRODUTO,T2.PRODUTO) AS PRODUTO,
        COALESCE(T1.IDADE_CORR,T2.IDADE_CORR) AS IDADE_CORR,
        T1.QTDE_AT_CPF_UNI AS REGISTROS_AT, 
        T1.QTDE_ESTOQUE_INICIAL AS ESTOQUE_INICIAL, 
        T1.QTDE_ESTOQUE_FINAL AS ESTOQUE_FINAL, 
        T1.QTDE_ENTRADAS AS ENTRADAS, 
        ((T1.QTDE_ESTOQUE_INICIAL + T1.QTDE_ESTOQUE_FINAL)/2) AS EXPOSICAOO, 
        T1.QTDE_ESTOQUE_INICIAL + T1.QTDE_ENTRADAS - T1.QTDE_ESTOQUE_FINAL AS SAIDAS_CALCULADAS,
        T2.QTDE_SA_CPF_UNI AS REGISTROS_SA,
        T2.INV_ACI, 
        T2.INV_ACI_TB, 
        T2.INV_DOE, 
        T2.INV_DOE_TB 

    FROM CTE_AT_INV  T1
    FULL OUTER JOIN CTE_SA_INV T2
    ON
        T1.REF_INFO = T2.REF_INFO 
        AND T1.COD_EMP = T2.COD_EMP
        AND T1.EMP = T2.EMP 
        AND T1.IDADE_CORR = T2.IDADE_CORR
        AND T1.COBERTURA = T2.COBERTURA
        AND T1.PRODUTO = T2.PRODUTO;