-- Contagem por individuo
CREATE VIEW TABELAO_VIEW_IND AS

-- SUBCONSULTA PARA DADOS DA AT_INV
WITH CTE_AT_INV AS
    ( -- Contagens a partir do criterio de individuos na tabela de ativos

    SELECT REF_INFO, EMP, COD_EMP, COBERTURA, SEXO_CORR, REF_INFO - EXTRACT(YEAR FROM DATA_NASC) AS IDADE, COUNT(*) AS QTDE_AT_IND,
     -- CALCULO ESTOQUES
        SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) < REF_INFO AND 
            EXTRACT(YEAR FROM DATA_INGR) > 1900
            THEN 1 ELSE 0 END) AS QTDE_ESTOQUE_INICIAL,
        SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) = 1900 THEN 1 ELSE 0 END) AS QTDE_ESTOQUE_FINAL,
        SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) = REF_INFO THEN 1 ELSE 0 END) AS QTDE_ENTRADAS,
        -- CALCULO DO TOTAL REGISTROS NO AGRUPAMENTO, SEM CONSIDERAR AS REPETIÇÕES DE QUEM É ESTOQUE FINAL (EM TESE ESSA CONTA DEVERIA SER ESTOQUE_INICIAL+ENTRADAS) 
        SUM(CASE WHEN EXTRACT(YEAR FROM DATA_INGR) > 1900 THEN 1 ELSE 0 END) 
        AS QTDE_GERAL_AT
    FROM 
    ( -- Nessa consulta eu agrupo os registros para o criterio de individuo, de modo que depois eu possa fazer as contagens para esse agrupamento
    SELECT REF_INFO, EMP, COD_EMP, CPF, COBERTURA, DATA_NASC, -- Verificar criterio de escolha para a cobertura
        CASE WHEN SEXO NOT IN ('M','F','m','f') THEN 'UNI' ELSE SEXO END SEXO_CORR,
        MIN(DATA_INGR) AS MIN_DATA_INGR,
        MAX(DATA_INGR) AS MAX_DATA_INGR
    FROM dados_parquet.at_inv_000
    WHERE LINHA_VALIDA = 1 AND ROWNUM = 100
    GROUP BY REF_INFO, EMP, COD_EMP, CPF, COBERTURA, DATA_NASC, CASE WHEN SEXO NOT IN ('M','F','m','f') THEN 'UNI' ELSE SEXO END 
    )  ATIVOS_INV_BASE

    GROUP BY REF_INFO, EMP, COD_EMP, COBERTURA, SEXO_CORR, REF_INFO - EXTRACT(YEAR FROM DATA_NASC)
    ),
 
CTE_SA_INV AS
    (-- Contagens a partir do criterio de individuos na tabela de saidas
    SELECT REF_INFO, EMP, COD_EMP, COBERTURA, SEXO_CORR, REF_INFO - EXTRACT(YEAR FROM DATA_NASC) AS IDADE, COUNT(*) AS QTDE_SA_IND, PRODUTO,
        SUM(CASE WHEN MOT_SAIDA = 400 THEN 1 ELSE 0 END) AS INV_ACI,
        SUM(CASE WHEN MOT_SAIDA = 500 THEN 1 ELSE 0 END) AS INV_ACI_TB,
        SUM(CASE WHEN MOT_SAIDA = 600 THEN 1 ELSE 0 END) AS INV_DOE,
        SUM(CASE WHEN MOT_SAIDA = 700 THEN 1 ELSE 0 END) AS INV_DOE_TB
    FROM 
    ( -- Nessa consulta eu agrupo os registros para o criterio de individuo, de modo que depois eu possa fazer as contagens para esse agrupamento
    SELECT REF_INFO, EMP, COD_EMP, CPF, COBERTURA, DATA_NASC, MOT_SAIDA,
        CASE WHEN SEXO NOT IN ('M','F','m','f') THEN 'UNI' ELSE SEXO END SEXO_CORR
    FROM dados_parquet.SA_INV_MOD
    WHERE LINHA_VALIDA = 1
    GROUP BY REF_INFO, EMP, COD_EMP, CPF, COBERTURA, DATA_NASC, MOT_SAIDA, CASE WHEN SEXO NOT IN ('M','F','m','f') THEN 'UNI' ELSE SEXO END
    ) SAIDAS_INV_BASE

    GROUP BY REF_INFO, EMP, COD_EMP, COBERTURA, SEXO_CORR, REF_INFO - EXTRACT(YEAR FROM DATA_NASC), PRODUTO
    )

-- CONSULTA FINAL PARA UNIR AS DUAS SUBCONSULTAS
    
SELECT 
    COALESCE(T1.REF_INFO,T2.REF_INFO) AS REF_INFO,
    COALESCE(T1.EMP,T2.EMP) AS EMP,
    COALESCE(T1.COD_EMP,T2.COD_EMP) AS COD_EMP,
    COALESCE(T1.COBERTURA,T2.COBERTURA) AS COBERTURA,
    COALESCE(T1.SEXO,T2.SEXO) AS SEXO,
    COALESCE(T1.IDADE,T2.IDADE) AS IDADE,
    COALESCE(T1.PRODUTO,T2.PRODUTO) AS PRODUTO, 
    T1.QTDE_AT_IND AS REGISTROS_AT, 
    T1.QTDE_ESTOQUE_INICIAL AS ESTOQUE_INICIAL, 
    T1.QTDE_ESTOQUE_FINAL AS ESTOQUE_FINAL, 
    T1.QTDE_ENTRADAS AS ENTRADAS, 
    ((T1.QTDE_ESTOQUE_INICIAL + T1.QTDE_ESTOQUE_FINAL)/2) AS EXPOSICAO, 
    T1.QTDE_ESTOQUE_INICIAL + T1.QTDE_ENTRADAS - T1.QTDE_ESTOQUE_FINAL AS SAIDAS_CALCULADAS,
    T2.QTDE_SA_IND AS REGISTROS_SA, 
    T2.INV_ACI, 
    T2.INV_ACI_TB, 
    T2.INV_DOE, 
    T2.INV_DOE_TB 

FROM CTE_AT_INV  T1
FULL OUTER JOIN CTE_SA_INV  T2
    ON
    T1.REF_INFO = T2.REF_INFO
    AND T1.COD_EMP = T2.COD_EMP
    AND T1.EMP = T2.EMP
    AND T1.IDADE = T2.IDADE
    AND T1.COBERTURA = T2.COBERTURA
    AND T1.SEXO_CORR = T2.SEXO_CORR
    AND T1.PRODUTO = T2.PRODUTO;
